// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"


namespace EscapeGameplayTags
{

#pragma region Player Tags
	/* Input Tags */
	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);

	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipWeapon);
	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipWeapon);
	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_FireWeapon);
	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ReloadWeapon);
	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UseGrenade);
	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SwitchCameraMode);

	/* Ability Tags */
	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Weapon);
	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Weapon);
	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Reload_Weapon);

	/* Weapon Tags */
	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Rifle);
	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Weapon);
	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Weapon);

	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_Weapon_Ammunition_Use);
	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Ranged);
	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_Weapon_Reload);

#pragma endregion

#pragma region Enemy Tags
	
	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);
	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged);

	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon_Left);
	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon_Right);

	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Strafing);
	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_UnderAttack);

#pragma endregion

#pragma region Shared Tags

	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);
	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);

	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);
	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_GrenadeHit);
	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_RangedHit);
	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_Respawn);

	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);

	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Dead);
	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Front);
	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Left);
	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Right);
	PROJECTESCAPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Back);

#pragma endregion
}